export enum EndpointKey {
  AUTH_SIGN_UP = "AUTH_SIGN_UP",
  AUTH_SIGN_IN = "AUTH_SIGN_IN",
  AUTH_SIGN_OUT = "AUTH_SIGN_OUT",
  AUTH_GET_SESSION = "AUTH_GET_SESSION",
  GET_CHILDREN = "GET_CHILDREN",
  CREATE_CHILD = "CREATE_CHILD",
  CHILD_LOGIN_PASSWORD = "CHILD_LOGIN_PASSWORD",
  CHILD_LOGIN_PIN = "CHILD_LOGIN_PIN",
  DEVICE_CHILDREN = "DEVICE_CHILDREN",
  CHAT_STREAM = "CHAT_STREAM",
}

export enum EndpointBehaviour {
  DEFAULT = "DEFAULT",
  ERROR = "ERROR",
  STALL = "STALL",
  NETWORK_ERROR = "NETWORK_ERROR",
}
